export const defaultSiteContent = {
  site: {
    title: "Amplizo - Marketing & Business Solution | Turn Clicks Into Customers",
    description:
      "We help local businesses grow with Google Business Profile optimization, digital marketing, and high-converting websites. Get more leads from Google.",
    whatsappNumber: "919876543210",
    whatsappMessage: "Hi, I'm interested in your digital marketing services",
    logo: {
      src: "/images/amplizo-logo.png",
      alt: "Amplizo - Marketing & Business Solution",
      sizes: {
        sm: { width: 164, height: 48, scale: 1.9, radius: "rounded-xl", paddingX: "px-3" },
        md: { width: 180, height: 56, scale: 1.9, radius: "rounded-xl", paddingX: "px-3" },
        lg: { width: 210, height: 64, scale: 1.95, radius: "rounded-2xl", paddingX: "px-4" },
      },
    },
  },
  navbar: {
    navItems: [
      { label: "Home", href: "#" },
      { label: "Services", href: "#services" },
      { label: "Portfolio", href: "#portfolio" },
      { label: "Case Studies", href: "#case-studies" },
      { label: "Contact", href: "#contact" },
    ],
    ctaLabel: "Book Free Consultation",
  },
  hero: {
    badge: "Trusted by 500+ Local Businesses",
    title: "Premium growth systems for",
    titleHighlight: "local business brands",
    description:
      "We turn discovery into booked calls, footfall, and repeat customers with sharper positioning, better websites, and performance-first local marketing.",
    proofPoints: [
      "Google Business Profile growth systems",
      "High-converting websites for local brands",
      "Performance marketing with measurable ROI",
    ],
    primaryCta: "Book Free Consultation",
    secondaryCta: "Chat on WhatsApp",
    roiLabel: "ROI Snapshot",
    roiValue: "4.8x",
    roiDescription: "avg. return on campaigns",
    pulseLabel: "Campaign Pulse",
    pulseValue: "+128%",
    pulseDescription: "More discovery calls from a tighter local funnel and better landing pages.",
    pulseStatus: "Live",
    conversionLabel: "Conversion Rate",
    conversionValue: "32%",
    stats: [
      { value: "10,000+", label: "Leads Generated", icon: "TrendingUp", tone: "text-primary bg-primary/12" },
      { value: "500+", label: "Businesses Served", icon: "Users", tone: "text-accent bg-accent/12" },
      { value: "300%", label: "Average Growth", icon: "Target", tone: "text-chart-4 bg-chart-4/12" },
    ],
    image: "/images/hero-dashboard.jpg",
    imageAlt: "Amplizo marketing dashboard showing analytics and lead generation metrics",
  },
  metricsBar: {
    eyebrow: "Trusted across local-first categories",
    subtext: "Built for operators who care about leads, bookings, and revenue",
    companies: [
      "Healthcare Clinics",
      "Fitness Studios",
      "Restaurants",
      "Real Estate",
      "Salons & Spas",
      "Legal Services",
      "Auto Services",
      "Home Services",
    ],
  },
  services: {
    eyebrow: "Our Services",
    title: "A premium growth stack for businesses that want",
    titleHighlight: "serious demand",
    description:
      "We combine positioning, performance marketing, and conversion design into one system so every touchpoint works harder.",
    note: "Every service is mapped to measurable lead and revenue goals.",
    learnMoreLabel: "Learn More",
    items: [
      {
        icon: "MapPin",
        title: "Google Business Profile",
        description: "Sharpen your map visibility, trust signals, and local discovery so more nearby buyers choose you first.",
        accent: "from-sky-500/15 to-blue-500/5",
      },
      {
        icon: "Target",
        title: "Google Ads Management",
        description: "Campaigns built for profitable demand capture, tighter targeting, and cleaner reporting on every rupee spent.",
        accent: "from-emerald-500/15 to-teal-500/5",
      },
      {
        icon: "Share2",
        title: "Social Media Marketing",
        description: "Consistent brand storytelling and local relevance across the channels your customers actually use.",
        accent: "from-cyan-500/15 to-sky-500/5",
      },
      {
        icon: "Globe",
        title: "Website Development",
        description: "Fast, conversion-led websites that make your business feel premium before the first call even happens.",
        accent: "from-indigo-500/15 to-blue-500/5",
      },
      {
        icon: "Search",
        title: "Local SEO",
        description: "Technical cleanup, authority building, and content strategy designed for high-intent local search terms.",
        accent: "from-amber-500/15 to-orange-500/5",
      },
      {
        icon: "Zap",
        title: "Lead Generation Systems",
        description: "Automated funnels, better follow-up, and cleaner attribution so you can scale without chaos.",
        accent: "from-violet-500/15 to-indigo-500/5",
      },
    ],
  },
  portfolio: {
    eyebrow: "Featured Work",
    title: "Designed to look premium. Built to",
    titleHighlight: "convert faster.",
    description:
      "Every project balances aesthetics, speed, and conversion clarity so the site works as hard as the ad spend behind it.",
    viewProjectLabel: "View Project",
    categories: ["All", "Healthcare", "Fitness", "Hospitality", "Beauty", "Real Estate", "Automotive"],
    items: [
      {
        title: "Smile Dental Care",
        category: "Healthcare",
        description: "Complete brand identity and website for a modern dental practice, including online booking and patient portal.",
        image: "/images/portfolio-clinic.jpg",
        services: ["Website Design", "GBP Optimization", "Google Ads"],
        results: "+280% patient inquiries",
      },
      {
        title: "FitZone Fitness",
        category: "Fitness",
        description: "Bold, energetic website with membership management, class scheduling, and lead generation funnels.",
        image: "/images/portfolio-gym.jpg",
        services: ["Website Design", "Social Media", "Lead Gen"],
        results: "+340% membership signups",
      },
      {
        title: "Spice Garden Restaurant",
        category: "Hospitality",
        description: "Elegant restaurant website with online menu, reservation system, and delivery integration.",
        image: "/images/portfolio-restaurant.jpg",
        services: ["Website Design", "Local SEO", "GBP Optimization"],
        results: "+210% online orders",
      },
      {
        title: "Glow Beauty Salon",
        category: "Beauty",
        description: "Luxurious salon website with service showcase, online booking, and customer loyalty features.",
        image: "/images/portfolio-salon.jpg",
        services: ["Website Design", "Instagram Ads", "GBP"],
        results: "+175% bookings",
      },
      {
        title: "Prime Properties",
        category: "Real Estate",
        description: "Professional real estate platform with property listings, virtual tours, and agent profiles.",
        image: "/images/portfolio-realestate.jpg",
        services: ["Website Design", "Google Ads", "Lead Gen"],
        results: "+420% qualified leads",
      },
      {
        title: "QuickFix Auto Service",
        category: "Automotive",
        description: "Service-focused auto shop website with appointment booking, service menu, and customer reviews.",
        image: "/images/portfolio-auto.jpg",
        services: ["Website Design", "Local SEO", "GBP"],
        results: "+195% service calls",
      },
    ],
  },
  howItWorks: {
    eyebrow: "How It Works",
    title: "From low visibility to a",
    titleHighlight: "reliable lead engine",
    description:
      "Our process is built to make growth feel structured, transparent, and commercially focused rather than chaotic.",
    steps: [
      {
        number: "01",
        icon: "Search",
        title: "Business Analysis",
        timeline: "Day 1-3",
        description:
          "We audit your search presence, website, reviews, and nearby competitors to identify where demand is leaking and where quick wins exist.",
        bullets: [
          "Google Business Profile audit and optimization score",
          "Website speed, UX, and conversion review",
          "Local search competitor benchmarking",
          "Review and reputation improvement plan",
        ],
      },
      {
        number: "02",
        icon: "Lightbulb",
        title: "Custom Strategy",
        timeline: "Day 4-7",
        description:
          "You get a sharper roadmap built around your market, your budget, and your highest-intent customer actions.",
        bullets: [
          "Keyword and offer positioning strategy",
          "Campaign and content planning",
          "Budget allocation by channel performance",
          "Lead funnel and tracking architecture",
        ],
      },
      {
        number: "03",
        icon: "Rocket",
        title: "Launch and Optimization",
        timeline: "Day 8-14",
        description:
          "We go live with landing pages, ad systems, profile improvements, and analytics so every move is measurable from day one.",
        bullets: [
          "Offer pages and landing flow improvements",
          "Campaign launch with location-based targeting",
          "Tracking setup for calls and forms",
          "Creative and copy deployment across channels",
        ],
      },
      {
        number: "04",
        icon: "BarChart3",
        title: "Scale What Works",
        timeline: "Day 15+",
        description:
          "We keep tightening the funnel, testing creative, and reallocating spend so growth becomes more predictable every month.",
        bullets: [
          "Weekly optimization cycles",
          "A/B testing on headlines, offers, and CTAs",
          "Monthly reporting tied to business outcomes",
          "Scaling recommendations for the best channels",
        ],
      },
    ],
    ctaLabel: "Start With a Free Strategy Call",
  },
  analytics: {
    eyebrow: "Proven Results",
    title: "We do not optimize for vanity. We optimize for",
    titleHighlight: "commercial lift.",
    description: "Calls, bookings, qualified leads, and better close-ready demand. That is the layer that matters.",
    stats: [
      { value: "8.4x", label: "Avg. Call Increase", description: "More calls within 90 days", icon: "Phone" },
      { value: "150+", label: "Businesses Served", description: "Across 12+ industries", icon: "Building2" },
      { value: "340%", label: "Avg. Traffic Growth", description: "Google search visibility", icon: "TrendingUp" },
      { value: "4.9", label: "Client Rating", description: "Based on 50+ reviews", icon: "Star" },
    ],
    featuresTitle: "Visibility, attribution, and performance in one view",
    features: [
      {
        icon: "BarChart3",
        title: "Real-Time Dashboards",
        description: "See traffic, leads, and conversion movement without waiting for end-of-month summaries.",
      },
      {
        icon: "PhoneCall",
        title: "Call Tracking",
        description: "Every phone lead is traced back to the campaign and page that created it.",
      },
      {
        icon: "FileText",
        title: "Clear Reporting",
        description: "Commercial reporting in plain English, focused on what moved pipeline and revenue.",
      },
      {
        icon: "DollarSign",
        title: "ROI-Led Planning",
        description: "Budget shifts toward channels that outperform, not toward vanity metrics.",
      },
    ],
    resultsTitle: "Average Client Results in 90 Days",
    resultsDescription:
      "A snapshot of the directional lift we typically create once positioning, campaigns, and conversion paths are aligned.",
    resultsDisclaimer:
      "Results vary by market, offer quality, competition, and budget, but the system is always built around measurable business outcomes.",
    metrics: [
      { label: "Google Traffic", before: 12, after: 89, unit: "%" },
      { label: "Monthly Calls", before: 8, after: 67, unit: "" },
      { label: "Maps Impressions", before: 2400, after: 18500, unit: "", showK: true },
      { label: "Conversion Rate", before: 1.2, after: 8.7, unit: "%" },
    ],
  },
  caseStudies: {
    eyebrow: "Case Studies",
    title: "Success Stories That",
    titleHighlight: "Speak for Themselves",
    description: "See how we've helped local businesses like yours achieve remarkable growth.",
    resultsHeading: "Results Achieved",
    items: [
      {
        industry: "Healthcare",
        business: "City Dental Clinic",
        description: "A dental clinic struggling to get new patients from Google.",
        image: "/images/case-dental.jpg",
        results: [
          { label: "Calls Increased", value: "+280%", icon: "Phone" },
          { label: "New Patients", value: "45/mo", icon: "Users" },
          { label: "Google Ranking", value: "#1", icon: "MapPin" },
        ],
      },
      {
        industry: "Fitness",
        business: "FitZone Gym",
        description: "A local gym looking to increase membership signups.",
        image: "/images/case-fitness.jpg",
        results: [
          { label: "Leads Generated", value: "+340%", icon: "ArrowUp" },
          { label: "New Members", value: "120/mo", icon: "Users" },
          { label: "Google Ranking", value: "#2", icon: "MapPin" },
        ],
      },
      {
        industry: "Restaurant",
        business: "Spice Garden",
        description: "An Indian restaurant wanting more dine-in and delivery orders.",
        image: "/images/case-restaurant.jpg",
        results: [
          { label: "Orders Increased", value: "+210%", icon: "ArrowUp" },
          { label: "Daily Calls", value: "35+", icon: "Phone" },
          { label: "Google Ranking", value: "#1", icon: "MapPin" },
        ],
      },
    ],
  },
  testimonials: {
    eyebrow: "Testimonials",
    title: "Trusted by operators who care about",
    titleHighlight: "real growth",
    description:
      "These are the outcomes clients remember most: stronger visibility, better leads, and calmer growth decisions.",
    items: [
      {
        name: "Dr. Priya Sharma",
        role: "Owner, City Dental Clinic",
        content: "Amplizo transformed our online presence. We went from 5 calls a week to over 40. The ROI has been incredible for our practice.",
        rating: 5,
        image: "/images/testimonial-1.jpg",
      },
      {
        name: "Rahul Verma",
        role: "Founder, FitZone Gym",
        content: "Best decision we made for our gym. The team understands local marketing like no one else. Our membership has doubled in 6 months.",
        rating: 5,
        image: "/images/testimonial-2.jpg",
      },
      {
        name: "Anita Desai",
        role: "Owner, Spice Garden",
        content: "From barely showing up on Google to being #1 in our area. The leads from Google Business Profile alone pay for the entire service.",
        rating: 5,
        image: "/images/testimonial-3.jpg",
      },
      {
        name: "Vikram Singh",
        role: "Director, Singh Real Estate",
        content: "Professional, responsive, and results-driven. They've helped us generate quality leads consistently month after month.",
        rating: 5,
        image: "/images/testimonial-1.jpg",
      },
    ],
  },
  leadMagnet: {
    eyebrow: "Limited Availability",
    title: "Get Your",
    titleHighlight: "FREE",
    titleSuffix: "Google Business Profile Audit",
    description: "Discover exactly why your competitors are outranking you and get a custom roadmap to fix it.",
    successTitle: "Your Audit is Being Prepared!",
    successDescription:
      "Check your inbox within 24 hours for your complete Google Business Profile audit with personalized recommendations.",
    successButton: "Book a Call to Review Results",
    formTitle: "Claim Your Free Audit Now",
    formDescription: "Fill out the form below and we'll send your audit within 24 hours.",
    submitLabel: "Get My Free Audit",
    submittingLabel: "Submitting...",
    socialProof: "143 business owners claimed their audit this month",
    privacyNote: "Your information is 100% secure. We never share or sell your data.",
    nameLabel: "Your Name",
    namePlaceholder: "John Smith",
    phoneLabel: "Phone Number",
    phonePlaceholder: "+91 98765 43210",
    businessLabel: "Business Name",
    businessPlaceholder: "Your Business Name",
    mapsLabel: "Google Maps Link or Website",
    mapsPlaceholder: "https://maps.google.com/...",
    urgencyItems: [
      { icon: "Zap", text: "Only 10 free audits/month" },
      { icon: "Clock", text: "Results in 24 hours" },
      { icon: "CreditCard", text: "No credit card required" },
    ],
    deliverables: [
      {
        icon: "Search",
        title: "Profile Completeness Score",
        description: "We analyze all 50+ GBP fields and show you exactly what's missing or incomplete.",
      },
      {
        icon: "BarChart3",
        title: "Local SEO Rankings Report",
        description: "See where you rank for your top 10 local keywords vs. your competitors.",
      },
      {
        icon: "Users",
        title: "Review Analysis",
        description: "Sentiment breakdown of your reviews with response strategy recommendations.",
      },
      {
        icon: "Target",
        title: "Quick-Win Action Items",
        description: "5 specific changes you can make this week to improve your visibility.",
      },
    ],
  },
  booking: {
    eyebrow: "Book a Call",
    title: "Schedule a premium strategy session with the",
    titleHighlight: "Amplizo team",
    description: "Pick a slot that works for you and we will come prepared with practical ideas tailored to your category.",
    badge: "30 minute discovery call",
    cardTitle: "Free Strategy Call",
    cardDescription: "Video meeting with growth and website recommendations",
    benefits: [
      "Discuss your growth goals and bottlenecks",
      "Get a market-specific acquisition strategy",
      "See where leads are leaking today",
      "No obligation, fully consultative call",
    ],
    dateLabel: "Select a Date",
    timeLabel: "Select a Time",
    confirmLabel: "Confirm Booking",
    selectedPrefix: "Selected:",
    timeSlots: ["10:00 AM", "11:00 AM", "12:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM"],
  },
  contact: {
    eyebrow: "Contact Us",
    title: "Let's build a sharper growth system for your",
    titleHighlight: "local brand",
    description: "Share a little about your business and we will come back with clear next steps, not generic sales talk.",
    cardTitle: "We build premium digital presence for ambitious local businesses.",
    cardDescription: "Prefer WhatsApp or a quick discovery call? Mention that in your message and we will follow up your way.",
    successTitle: "Message Sent",
    successDescription: "Thanks for reaching out. We'll get back to you within 24 hours with the next best step.",
    submitLabel: "Send Message",
    submittingLabel: "Sending...",
    visitLabel: "Visit or call us",
    nameLabel: "Your Name",
    namePlaceholder: "John Smith",
    phoneLabel: "Phone Number",
    phonePlaceholder: "+91 98765 43210",
    businessLabel: "Business Name",
    businessPlaceholder: "Your Business Name",
    serviceLabel: "Service Needed",
    servicePlaceholder: "Select a service",
    messageLabel: "Your Message",
    messagePlaceholder: "Tell us about your business and goals...",
    serviceOptions: [
      "Google Business Profile Optimization",
      "Google Ads Management",
      "Social Media Marketing",
      "Website Development",
      "Local SEO",
      "Lead Generation Systems",
      "Other",
    ],
    info: [
      { icon: "MapPin", label: "Address", value: "123 Business Park, Tech City, India 400001" },
      { icon: "Phone", label: "Phone", value: "+91 98765 43210" },
      { icon: "Mail", label: "Email", value: "hello@amplizo.com" },
      { icon: "Clock", label: "Hours", value: "Mon - Sat: 9:00 AM - 6:00 PM" },
    ],
  },
  footer: {
    description:
      "We help local businesses grow with Google Business Profile optimization, digital marketing, and high-converting websites.",
    rightsText: "Amplizo. All rights reserved.",
    madeWithText: "Made with care for local businesses",
    linkGroups: {
      services: [
        { label: "Google Business Profile", href: "/services#google-business-profile" },
        { label: "Google Ads", href: "/services#google-ads-management" },
        { label: "Social Media Marketing", href: "/services#social-media-marketing" },
        { label: "Website Development", href: "/services#website-development" },
        { label: "Local SEO", href: "/services#local-seo" },
        { label: "Lead Generation", href: "/services#lead-generation-systems" },
      ],
      company: [
        { label: "About Us", href: "/about" },
        { label: "Case Studies", href: "/#case-studies" },
        { label: "Blog", href: "/blog" },
        { label: "Careers", href: "/careers" },
        { label: "Contact", href: "/#contact" },
      ],
      support: [
        { label: "Help Center", href: "/help-center" },
        { label: "Privacy Policy", href: "/privacy-policy" },
        { label: "Terms of Service", href: "/terms-of-service" },
        { label: "Cookie Policy", href: "/cookie-policy" },
      ],
    },
    socialLinks: [
      { icon: "Facebook", href: "https://facebook.com/amplizo", label: "Facebook" },
      { icon: "Twitter", href: "https://twitter.com/amplizo", label: "Twitter" },
      { icon: "Instagram", href: "https://instagram.com/amplizo", label: "Instagram" },
      { icon: "Linkedin", href: "https://linkedin.com/company/amplizo", label: "LinkedIn" },
    ],
  },
} as const

export type SiteContent = typeof defaultSiteContent
